version: '3.8'

services:
  # Postgres service
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  # DumbKV service
  dumbkv:
    build:
      context: .
      target: dumbkv-main
    environment:
      - DATABASE_TYPE=postgres
      - DATABASE_LOCATION=postgres://postgres:postgres@postgres:5432/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 8000:8000
    depends_on:
      - postgres

volumes:
  postgres_data:
  
    
