name: Docker build image
on:
  push:

jobs:
  build_and_push:
    runs-on: ubuntu-latest #run on a linux machine powered by ubuntu
    permissions:
      id-token: write #This allows GitHub Actions job to get an OIDC token for signing.
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Build and push image
        run: |
          docker login --username lisaeileen --password ${{ secrets.GHCR_PAT }} ghcr.io
          docker build . --tag ghcr.io/lisaeileen/dumbkv2:latest
          docker push ghcr.io/lisaeileen/dumbkv:latest
