name: Docker build image
on:
  push:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push image
        env:
          IMAGE_NAME: ghcr.io/lisaeileen/dumbkv:latest
        run: |
          docker build . -t $IMAGE_NAME
          docker push $IMAGE_NAME
